- name: set fully qualified domain names and hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1 {% for hostname_domain in hostname_domains %}{{ hostname_hostname }}.{{ hostname_domain }} {% for hostname_alias in hostname_aliases %}{{ hostname_alias }}.{{ hostname_domain }} {% endfor %}{% endfor %} {{ hostname_hostname }}"
    state: present

- name: set hostname in /etc/hostname
  copy:
    dest: /etc/hostname
    content: "{{ hostname_hostname }}"

- name: set hostname via hostname command
  hostname:
    name: "{{ hostname_hostname }}"
